[package]
name = "database_orchestration"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = { workspace = true, features = ["serde", "serde-json", "string-only"] }
database = { path = "../database" }  # Reference the local workspace member directly
anyhow = { workspace = true }
bincode = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
splimes = { path = "../splimes"}
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
rand = { workspace = true }
num_cpus = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }
indexmap = { workspace = true, features = ["serde", "rayon"] }
flume = { workspace = true }
wide = { workspace = true }
ahash = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
serial_test = {workspace =  true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

