//! Workload profiles and seeded dataset generation.
//!
//! The flagship profile is [`InterpolationProfile::interpolation_heavy_irregular`],
//! the roadmap's first benchmark profile (Immediate Next Action #2). It produces
//! an irregularly-spaced, gap-containing series over a fixed time span and asks
//! the adapter to reconstruct a dense regular grid — the workload where DSP is
//! meant to win.
//!
//! Generation is fully seeded (`rand_chacha`) so a published seed regenerates the
//! exact dataset on any machine, satisfying the reproducibility requirement.

use bigdecimal::{BigDecimal, FromPrimitive};
use chrono::{DateTime, Duration, TimeZone, Utc};
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use splimes::{Point, Resolution, Spline};

/// A fixed epoch anchor for generated datasets.
///
/// Using a constant start (rather than "now") keeps generated datasets stable
/// across machines and runs, which the benchmark reproducibility rules require.
/// 2020-01-01T00:00:00Z.
const EPOCH_ANCHOR_SECS: i64 = 1_577_836_800;

/// Default seed for the flagship profile. Published in results so the dataset
/// can be regenerated byte-for-byte.
const DEFAULT_SEED: u64 = 0x00DB_5EED_0001;

/// A reproducible interpolation workload profile.
///
/// The generated dataset is a smooth underlying signal (a sum of sinusoids)
/// sampled at irregular instants with a fraction of samples dropped to create
/// gaps. The adapter is then asked to interpolate a dense regular grid at
/// `resolution` using `spline`.
#[derive(Debug, Clone, PartialEq)]
pub struct InterpolationProfile {
	/// Human-readable profile name, recorded in results.
	pub name: String,
	/// RNG seed; publishing this regenerates the dataset exactly.
	pub seed: u64,
	/// Number of input samples to emit (after applying missingness).
	pub input_points: usize,
	/// Fraction of regularly-spaced candidate samples to drop (`0.0..=1.0`).
	pub missingness_fraction: f64,
	/// Maximum timestamp jitter as a fraction of the nominal spacing
	/// (`0.0` = perfectly regular, `1.0` = up to a full step of jitter).
	pub jitter_fraction: f64,
	/// Total span of the series.
	pub span: Duration,
	/// Spline method requested of the adapter.
	pub spline: Spline,
	/// Output grid resolution requested of the adapter.
	pub resolution: Resolution,
}

impl InterpolationProfile {
	/// The flagship `interpolation-heavy-irregular` profile.
	///
	/// A one-day span sampled with ~480 irregular, jittered points and 20% of
	/// the grid dropped as gaps, reconstructed to a per-minute cubic grid
	/// (~1440 output points). Sized to exercise the full interpolation path
	/// while staying fast enough for a unit-test smoke run.
	#[must_use]
	pub fn interpolation_heavy_irregular() -> Self {
		Self { name: "interpolation-heavy-irregular".to_string(), seed: DEFAULT_SEED, input_points: 480, missingness_fraction: 0.20, jitter_fraction: 0.6, span: Duration::days(1), spline: Spline::Cubic, resolution: Resolution::Minutes }
	}

	/// Start instant of the generated series (the fixed epoch anchor).
	///
	/// # Panics
	///
	/// Panics only if [`EPOCH_ANCHOR_SECS`] is not a representable UTC instant,
	/// which cannot happen for the compiled-in constant.
	#[must_use]
	pub fn start(&self) -> DateTime<Utc> {
		Utc.timestamp_opt(EPOCH_ANCHOR_SECS, 0).single().expect("valid fixed epoch anchor")
	}

	/// End instant of the generated series (`start + span`).
	#[must_use]
	pub fn end(&self) -> DateTime<Utc> {
		self.start() + self.span
	}

	/// Generate the seeded, irregular, gap-containing input series.
	///
	/// The result is sorted by timestamp and contains at least two points so
	/// that every spline method has something to interpolate between.
	#[must_use]
	pub fn generate(&self) -> Vec<Point> {
		let mut rng = ChaCha8Rng::seed_from_u64(self.seed);
		let start = self.start();
		let span_ns = self.span.num_nanoseconds().unwrap_or(0).max(1);

		// Candidate count is inflated so that, after dropping `missingness`, we
		// still land near `input_points`.
		let keep = 1.0 - self.missingness_fraction.clamp(0.0, 0.95);
		#[allow(clippy::cast_precision_loss, clippy::cast_possible_truncation, clippy::cast_sign_loss)]
		let candidates = ((self.input_points as f64) / keep.max(0.05)).ceil() as usize;
		let candidates = candidates.max(2);

		// `candidates` is small (bounded by ~input_points); the i64 casts of the
		// loop index and count cannot wrap in practice.
		#[allow(clippy::cast_possible_wrap)]
		let nominal_step_ns = span_ns / candidates as i64;

		let mut points: Vec<Point> = Vec::with_capacity(self.input_points);
		for i in 0..candidates {
			// Drop samples to create gaps / block missingness.
			if rng.random::<f64>() < self.missingness_fraction {
				continue;
			}

			// Irregular spacing: nominal grid instant plus bounded jitter.
			#[allow(clippy::cast_possible_wrap)]
			let base_offset = nominal_step_ns.saturating_mul(i as i64);
			// Jitter span is a small fraction of one step; precision/truncation
			// in the f64 round-trip is intended and harmless.
			#[allow(clippy::cast_precision_loss, clippy::cast_possible_truncation)]
			let jitter_span = (nominal_step_ns as f64 * self.jitter_fraction) as i64;
			let jitter = if jitter_span > 0 { rng.random_range(-jitter_span..=jitter_span) } else { 0 };
			let offset_ns = (base_offset + jitter).clamp(0, span_ns);
			let timestamp = start + Duration::nanoseconds(offset_ns);

			// Smooth underlying signal so interpolation is meaningful, plus a
			// little noise. Frequencies chosen to vary within the span.
			#[allow(clippy::cast_precision_loss)]
			let phase = offset_ns as f64 / span_ns as f64;
			let wave_3 = (phase * std::f64::consts::TAU * 3.0).sin();
			let wave_11 = (phase * std::f64::consts::TAU * 11.0).sin();
			let noise = rng.random_range(-2.0..2.0);
			let signal = 10.0_f64.mul_add(wave_11, 30.0_f64.mul_add(wave_3, 50.0)) + noise;
			let value = BigDecimal::from_f64(signal).unwrap_or_else(|| BigDecimal::from(0));
			points.push(Point { timestamp, value });
		}

		points.sort_by_key(|p| p.timestamp);

		// Guarantee at least two distinct points for any spline.
		if points.len() < 2 {
			points.clear();
			points.push(Point { timestamp: start, value: BigDecimal::from(50) });
			points.push(Point { timestamp: self.end(), value: BigDecimal::from(60) });
		}

		points
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn generation_is_deterministic_for_a_seed() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let a = profile.generate();
		let b = profile.generate();
		assert_eq!(a.len(), b.len(), "same seed -> same point count");
		assert_eq!(a, b, "same seed -> identical points");
	}

	#[test]
	fn generated_series_is_sorted_and_in_range() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let points = profile.generate();
		assert!(points.len() >= 2);
		let (start, end) = (profile.start(), profile.end());
		for w in points.windows(2) {
			assert!(w[0].timestamp <= w[1].timestamp, "timestamps must be sorted");
		}
		assert!(points.first().unwrap().timestamp >= start);
		assert!(points.last().unwrap().timestamp <= end);
	}

	#[test]
	fn missingness_thins_the_series_below_candidate_count() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let points = profile.generate();
		// With 20% missingness we expect noticeably fewer than 2x input_points.
		assert!(points.len() < profile.input_points * 2);
		assert!(points.len() > profile.input_points / 2);
	}
}
