[package]
name = "weft-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
database = { path = "../database" }
splimes = { path = "../splimes" }
tokio = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
num-traits = "0.2"
tracing = { workspace = true }
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true }
dirs = { workspace = true }
csv = { workspace = true }
bigdecimal = { workspace = true }