pub use cubic::{CUBIC_INTERPOLATION_SHADER, CUBIC_INTERPOLATION_SHADER_F64};
pub use linear::{LINEAR_INTERPOLATION_SHADER_F32, LINEAR_INTERPOLATION_SHADER_F64};
pub use polynomial::{POLYNOMIAL_INTERPOLATION_SHADER, POLYNOMIAL_INTERPOLATION_SHADER_F64};
pub use quadratic::{QUADRATIC_INTERPOLATION_SHADER, QUADRATIC_INTERPOLATION_SHADER_F64};

mod cubic;
mod linear;
mod polynomial;
mod quadratic;
