[package]
name = "dsm_source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
dsm_asset = { path = "../dsm-asset" }
serde_json = "1"
reqwest = { version="0", features= ["json"] }