//! Workload profiles and seeded dataset generation.
//!
//! The flagship profile is [`InterpolationProfile::interpolation_heavy_irregular`],
//! the roadmap's first benchmark profile (Immediate Next Action #2). It produces
//! an irregularly-spaced, gap-containing series over a fixed time span and asks
//! the adapter to reconstruct a dense regular grid — the workload where WeftDB is
//! meant to win.
//!
//! Generation is fully seeded (`rand_chacha`) so a published seed regenerates the
//! exact dataset on any machine, satisfying the reproducibility requirement.

use bigdecimal::{BigDecimal, FromPrimitive};
use chrono::{DateTime, Duration, TimeZone, Utc};
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use serde::{Deserialize, Serialize};
use splimes::{Point, Resolution, Spline};

use crate::line_protocol::{parse_points, ParseError, TimestampPrecision};

/// A fixed epoch anchor for generated datasets.
///
/// Using a constant start (rather than "now") keeps generated datasets stable
/// across machines and runs, which the benchmark reproducibility rules require.
/// 2020-01-01T00:00:00Z.
const EPOCH_ANCHOR_SECS: i64 = 1_577_836_800;

/// Default seed for the flagship profile. Published in results so the dataset
/// can be regenerated byte-for-byte.
pub const DEFAULT_SEED: u64 = 0x00DB_5EED_0001;

/// Default additive-noise amplitude (`±` this value) for the synthetic signal.
pub const DEFAULT_NOISE_AMPLITUDE: f64 = 2.0;

/// Where a profile's input series comes from.
///
/// The flagship profile uses [`DatasetSource::Generated`] — a seeded, fully
/// reproducible synthetic series. [`DatasetSource::LineProtocol`] instead drives
/// the *same* interpolation workload from a real `InfluxDB`-Line-Protocol / TSBS
/// payload (parsed via [`crate::line_protocol::parse_points`]), so a customer- or
/// TSBS-supplied dataset flows through the identical harness and correctness gate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DatasetSource {
	/// A seeded synthetic series, regenerated on demand from the profile's seed.
	Generated,
	/// A fixed series parsed from a line-protocol payload, sorted by timestamp.
	LineProtocol {
		/// The parsed input points (sorted, at least two, spanning a non-zero range).
		points: Vec<Point>,
	},
}

/// Why a profile could not be built from a line-protocol payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LineProtocolProfileError {
	/// The payload was structurally malformed (carries the underlying parse error).
	Parse(ParseError),
	/// Fewer than two usable points projected onto the chosen field — a spline
	/// needs at least two points to interpolate between. Carries the count found.
	TooFewPoints(usize),
	/// All usable points share a single instant, so the series spans no time and
	/// there is no grid to interpolate onto.
	ZeroSpan,
}

impl std::fmt::Display for LineProtocolProfileError {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			Self::Parse(e) => write!(f, "line-protocol parse failed: {e}"),
			Self::TooFewPoints(n) => write!(f, "need at least two points to interpolate, found {n}"),
			Self::ZeroSpan => write!(f, "all points share one instant; the series spans no time"),
		}
	}
}

impl std::error::Error for LineProtocolProfileError {
	fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
		match self {
			Self::Parse(e) => Some(e),
			Self::TooFewPoints(_) | Self::ZeroSpan => None,
		}
	}
}

impl From<ParseError> for LineProtocolProfileError {
	fn from(e: ParseError) -> Self {
		Self::Parse(e)
	}
}

/// The analytic shape of the synthetic generator's noise-free underlying signal.
///
/// Every shape is a deterministic function of a fractional `phase` in `[0, 1]`
/// across the series span, bounded to `[10, 90]`, so an accuracy benchmark always
/// has a known ground truth in a fixed range regardless of shape. The shapes
/// stress reconstruction methods differently, which is exactly what makes them
/// worth varying: a smooth [`SignalShape::MultiSine`] favors a cubic spline; a
/// [`SignalShape::Sawtooth`] or [`SignalShape::Step`] has sharp discontinuities
/// that punish a cubic's overshoot and play to forward-fill's strength near the
/// jump; a [`SignalShape::DampedSine`] mixes a decaying smooth oscillation. The
/// research foundation calls for benchmarking interpolation *quality* (extrema
/// preservation, behavior near block missingness) across diverse signals, not
/// only speed on one curve.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SignalShape {
	/// The flagship signal: a sum of two sinusoids (3 and 11 cycles), `50 ± 40`.
	#[default]
	MultiSine,
	/// A periodic rising ramp that resets sharply — five ramps across the span,
	/// each a discontinuity a smooth spline cannot follow without overshoot.
	Sawtooth,
	/// A periodic square wave alternating between two levels (`20`/`80`) — the
	/// piecewise-constant shape forward-fill reconstructs exactly between edges.
	Step,
	/// A decaying oscillation: a six-cycle sine whose `±40` amplitude shrinks
	/// across the span toward the `50` midline.
	DampedSine,
}

impl SignalShape {
	/// Evaluate the shape's noise-free value at fractional `phase` in `[0, 1]`.
	///
	/// The result is always finite and within `[10, 90]` for any `phase` in range.
	#[must_use]
	pub fn evaluate(self, phase: f64) -> f64 {
		use std::f64::consts::TAU;
		match self {
			Self::MultiSine => {
				let wave_3 = (phase * TAU * 3.0).sin();
				let wave_11 = (phase * TAU * 11.0).sin();
				10.0_f64.mul_add(wave_11, 30.0_f64.mul_add(wave_3, 50.0))
			}
			Self::Sawtooth => {
				// Five rising ramps over the span; `fract` resets each sharply.
				let frac = (phase * 5.0).fract();
				80.0_f64.mul_add(frac, 10.0)
			}
			Self::Step => {
				// Six half-periods alternating 20/80 with sharp edges. `phase` is
				// in `[0, 1]`, so `phase * 6.0` is in `[0, 6]` and the cast cannot
				// wrap; truncation toward zero equals `floor` for a non-negative.
				#[allow(clippy::cast_possible_truncation)]
				let half = (phase * 6.0) as i64;
				if half % 2 == 0 {
					20.0
				} else {
					80.0
				}
			}
			Self::DampedSine => {
				// A six-cycle sine whose ±40 amplitude decays toward ±5 by span end.
				let decay = (-2.0 * phase).exp();
				let wave = (phase * TAU * 6.0).sin();
				(40.0 * decay).mul_add(wave, 50.0)
			}
		}
	}
}

/// The tunable knobs for a synthetic interpolation profile (everything except the
/// human-readable name).
///
/// [`Default`] yields the flagship `interpolation-heavy-irregular` configuration,
/// so overriding one field while keeping the rest is a `..Default::default()`
/// away. Grouping the knobs here (rather than passing seven positional arguments)
/// keeps [`InterpolationProfile::synthetic`] readable and call sites self-documenting.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SyntheticParams {
	/// RNG seed; publishing it regenerates the dataset exactly.
	pub seed: u64,
	/// Post-missingness target sample count.
	pub input_points: usize,
	/// Fraction of regularly-spaced candidate samples to drop (`0.0..=1.0`).
	pub missingness_fraction: f64,
	/// Maximum timestamp jitter as a fraction of the nominal spacing (`0.0..=1.0`).
	pub jitter_fraction: f64,
	/// Additive sample-noise amplitude (`±`); `0.0` puts samples on the ground truth.
	pub noise_amplitude: f64,
	/// Analytic shape of the noise-free underlying signal (the ground truth).
	pub signal_shape: SignalShape,
	/// Spline method requested of the adapter.
	pub spline: Spline,
	/// Output grid resolution requested of the adapter.
	pub resolution: Resolution,
}

impl Default for SyntheticParams {
	/// The flagship `interpolation-heavy-irregular` knob set: 480 irregular samples
	/// over a day, 20% gaps, 0.6 jitter, ±2.0 noise, a multi-sine signal, per-minute
	/// cubic reconstruction.
	fn default() -> Self {
		Self { seed: DEFAULT_SEED, input_points: 480, missingness_fraction: 0.20, jitter_fraction: 0.6, noise_amplitude: DEFAULT_NOISE_AMPLITUDE, signal_shape: SignalShape::MultiSine, spline: Spline::Cubic, resolution: Resolution::Minutes }
	}
}

/// A reproducible interpolation workload profile.
///
/// The generated dataset is a smooth underlying signal (a sum of sinusoids)
/// sampled at irregular instants with a fraction of samples dropped to create
/// gaps. The adapter is then asked to interpolate a dense regular grid at
/// `resolution` using `spline`.
#[derive(Debug, Clone, PartialEq)]
pub struct InterpolationProfile {
	/// Human-readable profile name, recorded in results.
	pub name: String,
	/// RNG seed; publishing this regenerates the dataset exactly.
	pub seed: u64,
	/// Number of input samples to emit (after applying missingness).
	pub input_points: usize,
	/// Fraction of regularly-spaced candidate samples to drop (`0.0..=1.0`).
	pub missingness_fraction: f64,
	/// Maximum timestamp jitter as a fraction of the nominal spacing
	/// (`0.0` = perfectly regular, `1.0` = up to a full step of jitter).
	pub jitter_fraction: f64,
	/// Amplitude of the additive sample noise (`±noise_amplitude`, uniform). `0.0`
	/// makes every sample lie exactly on the analytic ground truth, isolating the
	/// reconstruction method's own error from measurement noise.
	pub noise_amplitude: f64,
	/// Analytic shape of the noise-free underlying signal. Selects the ground truth
	/// the generator samples and an accuracy benchmark scores against. Unused for a
	/// [`DatasetSource::LineProtocol`] profile, which carries no analytic truth.
	pub signal_shape: SignalShape,
	/// Total span of the series.
	pub span: Duration,
	/// Spline method requested of the adapter.
	pub spline: Spline,
	/// Output grid resolution requested of the adapter.
	pub resolution: Resolution,
	/// Where the input series comes from (synthetic generation vs a parsed
	/// line-protocol payload). The rest of the harness is identical either way.
	pub source: DatasetSource,
}

impl InterpolationProfile {
	/// The flagship `interpolation-heavy-irregular` profile.
	///
	/// A one-day span sampled with ~480 irregular, jittered points and 20% of
	/// the grid dropped as gaps, reconstructed to a per-minute cubic grid
	/// (~1440 output points). Sized to exercise the full interpolation path
	/// while staying fast enough for a unit-test smoke run.
	#[must_use]
	pub fn interpolation_heavy_irregular() -> Self {
		Self::synthetic("interpolation-heavy-irregular", SyntheticParams::default())
	}

	/// Build a synthetic interpolation profile over a one-day span from an explicit
	/// [`SyntheticParams`] knob set.
	///
	/// This is the constructor the CLI's `--synthetic` mode drives: the params let
	/// a caller dial the seed, sample count, missingness, jitter, noise amplitude,
	/// spline, and output resolution while keeping the [`DatasetSource::Generated`]
	/// signal (and thus a known analytic ground truth for accuracy scoring).
	#[must_use]
	pub fn synthetic(name: impl Into<String>, params: SyntheticParams) -> Self {
		let SyntheticParams { seed, input_points, missingness_fraction, jitter_fraction, noise_amplitude, signal_shape, spline, resolution } = params;
		Self { name: name.into(), seed, input_points, missingness_fraction, jitter_fraction, noise_amplitude, signal_shape, span: Duration::days(1), spline, resolution, source: DatasetSource::Generated }
	}

	/// Build a profile whose input series is parsed from an `InfluxDB`
	/// Line-Protocol / TSBS payload, projecting the chosen numeric `field` onto
	/// `splimes::Point`s and driving the same interpolation workload as the
	/// generated profiles. This is the TSBS on-ramp: a real or customer-supplied
	/// `.lp` file flows through the identical harness, correctness gate, and
	/// reporting as the synthetic flagship profile.
	///
	/// The parsed series is fixed (not regenerated), so [`Self::generate`] returns
	/// a clone of it and [`Self::start`] / [`Self::end`] derive from the data's own
	/// timestamp bounds rather than the synthetic epoch anchor. `seed` is recorded
	/// as `0` and `missingness_fraction` as `0.0` — the data is taken as given, not
	/// synthesized — while `span` reflects the data's actual extent.
	///
	/// # Errors
	///
	/// Returns [`LineProtocolProfileError::Parse`] if the payload is structurally
	/// malformed, [`LineProtocolProfileError::TooFewPoints`] if fewer than two
	/// records carry the field and a timestamp, or [`LineProtocolProfileError::ZeroSpan`]
	/// if every usable point shares a single instant (no grid to interpolate onto).
	pub fn from_line_protocol(name: impl Into<String>, payload: &str, field: &str, precision: TimestampPrecision, spline: Spline, resolution: Resolution) -> Result<Self, LineProtocolProfileError> {
		let points = parse_points(payload, field, precision)?;
		if points.len() < 2 {
			return Err(LineProtocolProfileError::TooFewPoints(points.len()));
		}
		// `parse_points` sorts by timestamp, so first/last are the series bounds.
		let (first, last) = (points[0].timestamp, points[points.len() - 1].timestamp);
		if first >= last {
			return Err(LineProtocolProfileError::ZeroSpan);
		}
		Ok(Self { name: name.into(), seed: 0, input_points: points.len(), missingness_fraction: 0.0, jitter_fraction: 0.0, noise_amplitude: 0.0, signal_shape: SignalShape::default(), span: last - first, spline, resolution, source: DatasetSource::LineProtocol { points } })
	}

	/// Start instant of the series.
	///
	/// For a [`DatasetSource::Generated`] profile this is the fixed epoch anchor;
	/// for a [`DatasetSource::LineProtocol`] profile it is the earliest input
	/// timestamp (the data carries its own bounds).
	///
	/// # Panics
	///
	/// Panics only if `EPOCH_ANCHOR_SECS` is not a representable UTC instant,
	/// which cannot happen for the compiled-in constant.
	#[must_use]
	pub fn start(&self) -> DateTime<Utc> {
		match &self.source {
			DatasetSource::Generated => Self::anchor(),
			// `from_line_protocol` guarantees a sorted, non-empty series, so the
			// first point is the lower bound; the anchor is an unreachable fallback.
			DatasetSource::LineProtocol { points } => points.first().map_or_else(Self::anchor, |p| p.timestamp),
		}
	}

	/// End instant of the series.
	///
	/// For a generated profile this is `start + span`; for a line-protocol profile
	/// it is the latest input timestamp.
	#[must_use]
	pub fn end(&self) -> DateTime<Utc> {
		match &self.source {
			DatasetSource::Generated => self.start() + self.span,
			DatasetSource::LineProtocol { points } => points.last().map_or_else(|| Self::anchor() + self.span, |p| p.timestamp),
		}
	}

	/// The fixed synthetic epoch anchor (2020-01-01T00:00:00Z).
	///
	/// # Panics
	///
	/// Panics only if `EPOCH_ANCHOR_SECS` is not a representable UTC instant,
	/// which cannot happen for the compiled-in constant.
	#[must_use]
	fn anchor() -> DateTime<Utc> {
		Utc.timestamp_opt(EPOCH_ANCHOR_SECS, 0).single().expect("valid fixed epoch anchor")
	}

	/// The analytic ground-truth shape this profile's synthetic data was generated
	/// from, or `None` for a [`DatasetSource::LineProtocol`] source (which carries
	/// no synthetic shape). Mirrors [`Self::clean_signal_at`]'s `None`-for-real-data
	/// contract and is what the result schema records for reproducibility.
	#[must_use]
	pub fn ground_truth_shape(&self) -> Option<SignalShape> {
		matches!(self.source, DatasetSource::Generated).then_some(self.signal_shape)
	}

	/// Evaluate the noise-free underlying signal at instant `t`, if this profile
	/// has an analytic ground truth (i.e. it is [`DatasetSource::Generated`]).
	///
	/// Returns `None` for a [`DatasetSource::LineProtocol`] profile, whose
	/// real-world input carries no known true signal to score against. `t` is
	/// projected onto the same `[0, 1]` phase the generator uses (offset from
	/// [`Self::start`] over the total `span`); instants outside `[start, end]` are
	/// clamped into the span so a boundary grid point still yields a defined value.
	#[must_use]
	#[allow(clippy::cast_precision_loss)]
	pub fn clean_signal_at(&self, t: DateTime<Utc>) -> Option<f64> {
		if !matches!(self.source, DatasetSource::Generated) {
			return None;
		}
		let span_ns = self.span.num_nanoseconds().unwrap_or(0).max(1);
		let offset_ns = (t - self.start()).num_nanoseconds().unwrap_or(0).clamp(0, span_ns);
		let phase = offset_ns as f64 / span_ns as f64;
		Some(self.signal_shape.evaluate(phase))
	}

	/// Produce the profile's input series.
	///
	/// For a [`DatasetSource::Generated`] profile this regenerates the seeded,
	/// irregular, gap-containing series (deterministic for the seed). For a
	/// [`DatasetSource::LineProtocol`] profile it returns a clone of the parsed
	/// series. Either way the result is sorted by timestamp and contains at least
	/// two points so that every spline method has something to interpolate between.
	#[must_use]
	pub fn generate(&self) -> Vec<Point> {
		match &self.source {
			DatasetSource::Generated => self.generate_synthetic(),
			DatasetSource::LineProtocol { points } => points.clone(),
		}
	}

	/// Generate the seeded, irregular, gap-containing synthetic series.
	#[must_use]
	fn generate_synthetic(&self) -> Vec<Point> {
		let mut rng = ChaCha8Rng::seed_from_u64(self.seed);
		let start = self.start();
		let span_ns = self.span.num_nanoseconds().unwrap_or(0).max(1);

		// Candidate count is inflated so that, after dropping `missingness`, we
		// still land near `input_points`.
		let keep = 1.0 - self.missingness_fraction.clamp(0.0, 0.95);
		#[allow(clippy::cast_precision_loss, clippy::cast_possible_truncation, clippy::cast_sign_loss)]
		let candidates = ((self.input_points as f64) / keep.max(0.05)).ceil() as usize;
		let candidates = candidates.max(2);

		// `candidates` is small (bounded by ~input_points); the i64 casts of the
		// loop index and count cannot wrap in practice.
		#[allow(clippy::cast_possible_wrap)]
		let nominal_step_ns = span_ns / candidates as i64;

		let mut points: Vec<Point> = Vec::with_capacity(self.input_points);
		for i in 0..candidates {
			// Drop samples to create gaps / block missingness.
			if rng.random::<f64>() < self.missingness_fraction {
				continue;
			}

			// Irregular spacing: nominal grid instant plus bounded jitter.
			#[allow(clippy::cast_possible_wrap)]
			let base_offset = nominal_step_ns.saturating_mul(i as i64);
			// Jitter span is a small fraction of one step; precision/truncation
			// in the f64 round-trip is intended and harmless.
			#[allow(clippy::cast_precision_loss, clippy::cast_possible_truncation)]
			let jitter_span = (nominal_step_ns as f64 * self.jitter_fraction) as i64;
			let jitter = if jitter_span > 0 { rng.random_range(-jitter_span..=jitter_span) } else { 0 };
			let offset_ns = (base_offset + jitter).clamp(0, span_ns);
			let timestamp = start + Duration::nanoseconds(offset_ns);

			// Underlying signal so interpolation is meaningful, plus a little noise.
			// The signal is the shared analytic ground truth (see [`SignalShape`])
			// evaluated through `self.signal_shape`, so accuracy scoring can never
			// drift from what was generated.
			#[allow(clippy::cast_precision_loss)]
			let phase = offset_ns as f64 / span_ns as f64;
			// A zero (or negative) amplitude means a noise-free sample sitting
			// exactly on the analytic ground truth; `random_range` requires a
			// non-empty range, so guard the degenerate case explicitly.
			let noise = if self.noise_amplitude > 0.0 { rng.random_range(-self.noise_amplitude..=self.noise_amplitude) } else { 0.0 };
			let signal = self.signal_shape.evaluate(phase) + noise;
			let value = BigDecimal::from_f64(signal).unwrap_or_else(|| BigDecimal::from(0));
			points.push(Point { timestamp, value });
		}

		points.sort_by_key(|p| p.timestamp);

		// Guarantee at least two distinct points for any spline.
		if points.len() < 2 {
			points.clear();
			points.push(Point { timestamp: start, value: BigDecimal::from(50) });
			points.push(Point { timestamp: self.end(), value: BigDecimal::from(60) });
		}

		points
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn generation_is_deterministic_for_a_seed() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let a = profile.generate();
		let b = profile.generate();
		assert_eq!(a.len(), b.len(), "same seed -> same point count");
		assert_eq!(a, b, "same seed -> identical points");
	}

	#[test]
	fn generated_series_is_sorted_and_in_range() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let points = profile.generate();
		assert!(points.len() >= 2);
		let (start, end) = (profile.start(), profile.end());
		for w in points.windows(2) {
			assert!(w[0].timestamp <= w[1].timestamp, "timestamps must be sorted");
		}
		assert!(points.first().unwrap().timestamp >= start);
		assert!(points.last().unwrap().timestamp <= end);
	}

	#[test]
	fn missingness_thins_the_series_below_candidate_count() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let points = profile.generate();
		// With 20% missingness we expect noticeably fewer than 2x input_points.
		assert!(points.len() < profile.input_points * 2);
		assert!(points.len() > profile.input_points / 2);
	}

	/// A small TSBS-style payload: one measurement, one tag, one numeric field,
	/// with timestamps in seconds (out of order on purpose so we can prove sorting).
	const SAMPLE_LP: &str = "cpu,host=h0 usage=10.0 0\n\
cpu,host=h0 usage=14.5 180\n\
cpu,host=h0 usage=12.0 60\n\
cpu,host=h0 usage=11.5 240\n\
cpu,host=h0 usage=13.0 120\n";

	#[test]
	fn from_line_protocol_parses_sorts_and_bounds_from_data() {
		let profile = InterpolationProfile::from_line_protocol("tsbs-cpu", SAMPLE_LP, "usage", TimestampPrecision::Seconds, Spline::Cubic, Resolution::Minutes).expect("valid payload builds a profile");

		assert_eq!(profile.name, "tsbs-cpu");
		assert!(matches!(profile.source, DatasetSource::LineProtocol { .. }));

		let points = profile.generate();
		assert_eq!(points.len(), 5, "all five records project onto the field");
		for w in points.windows(2) {
			assert!(w[0].timestamp <= w[1].timestamp, "series must be sorted by timestamp");
		}

		// Bounds derive from the data (epoch + 0s .. epoch + 240s), not the anchor.
		assert_eq!(profile.start(), Utc.timestamp_opt(0, 0).single().unwrap());
		assert_eq!(profile.end(), Utc.timestamp_opt(240, 0).single().unwrap());
		assert_eq!(profile.span, Duration::seconds(240));
		// A line-protocol profile records no synthetic seed / missingness.
		assert_eq!(profile.seed, 0);
		assert!((profile.missingness_fraction - 0.0).abs() < f64::EPSILON);
	}

	#[test]
	fn from_line_protocol_skips_records_missing_the_field() {
		// Only two of the three records carry `usage`; the middle one is dropped.
		let payload = "cpu,host=h0 usage=10.0 0\ncpu,host=h0 other=99i 60\ncpu,host=h0 usage=12.0 120\n";
		let profile = InterpolationProfile::from_line_protocol("tsbs-cpu", payload, "usage", TimestampPrecision::Seconds, Spline::Linear, Resolution::Minutes).expect("two usable points is enough");
		assert_eq!(profile.generate().len(), 2);
	}

	#[test]
	fn from_line_protocol_rejects_too_few_points() {
		let payload = "cpu,host=h0 usage=10.0 0\n";
		let err = InterpolationProfile::from_line_protocol("x", payload, "usage", TimestampPrecision::Seconds, Spline::Linear, Resolution::Minutes).expect_err("one point cannot drive interpolation");
		assert_eq!(err, LineProtocolProfileError::TooFewPoints(1));
	}

	#[test]
	fn from_line_protocol_rejects_zero_span() {
		// Two points sharing one instant span no time, so there is no grid.
		let payload = "cpu,host=h0 usage=10.0 60\ncpu,host=h0 usage=12.0 60\n";
		let err = InterpolationProfile::from_line_protocol("x", payload, "usage", TimestampPrecision::Seconds, Spline::Linear, Resolution::Minutes).expect_err("a zero-span series must be rejected");
		assert_eq!(err, LineProtocolProfileError::ZeroSpan);
	}

	#[test]
	fn clean_signal_at_is_defined_in_range_for_a_generated_profile() {
		let profile = InterpolationProfile::interpolation_heavy_irregular();
		let (start, end) = (profile.start(), profile.end());
		// Endpoints and the midpoint must all yield a finite truth within [10, 90].
		for t in [start, start + (end - start) / 2, end] {
			let truth = profile.clean_signal_at(t).expect("generated profile has ground truth");
			assert!(truth.is_finite(), "ground truth must be finite at {t}");
			assert!((10.0..=90.0).contains(&truth), "signal must stay in [10, 90], got {truth} at {t}");
		}
		// Instants outside the span clamp into it rather than returning garbage.
		assert_eq!(profile.clean_signal_at(start - Duration::days(1)), profile.clean_signal_at(start), "before-start clamps to start");
		assert_eq!(profile.clean_signal_at(end + Duration::days(1)), profile.clean_signal_at(end), "after-end clamps to end");
	}

	#[test]
	fn zero_noise_samples_lie_exactly_on_the_ground_truth() {
		use bigdecimal::ToPrimitive;
		// No noise: every generated sample's value must equal the analytic ground
		// truth at its own (jittered) timestamp, so the only reconstruction error a
		// benchmark sees is the method's own — not measurement noise.
		let profile = InterpolationProfile::synthetic("clean", SyntheticParams { seed: 7, input_points: 100, missingness_fraction: 0.0, jitter_fraction: 0.5, noise_amplitude: 0.0, signal_shape: SignalShape::MultiSine, spline: Spline::Cubic, resolution: Resolution::Minutes });
		let points = profile.generate();
		assert!(points.len() >= 2);
		for p in &points {
			let truth = profile.clean_signal_at(p.timestamp).expect("generated profile has ground truth");
			let value = p.value.to_f64().expect("finite value");
			assert!((value - truth).abs() < 1e-9, "zero-noise sample must lie on ground truth: value {value} vs truth {truth}");
		}
	}

	#[test]
	fn clean_signal_at_has_no_ground_truth_for_a_line_protocol_profile() {
		let profile = InterpolationProfile::from_line_protocol("tsbs-cpu", SAMPLE_LP, "usage", TimestampPrecision::Seconds, Spline::Cubic, Resolution::Minutes).expect("valid payload builds a profile");
		assert!(profile.clean_signal_at(profile.start()).is_none(), "real-world data carries no analytic ground truth");
	}

	#[test]
	fn every_signal_shape_stays_finite_and_in_range() {
		// All four shapes must be bounded to [10, 90] across the whole phase domain
		// so an accuracy benchmark has a known-range ground truth regardless of shape.
		for shape in [SignalShape::MultiSine, SignalShape::Sawtooth, SignalShape::Step, SignalShape::DampedSine] {
			for i in 0..=1000 {
				let phase = f64::from(i) / 1000.0;
				let v = shape.evaluate(phase);
				assert!(v.is_finite() && (10.0..=90.0).contains(&v), "{shape:?} out of range at phase {phase}: {v}");
			}
		}
	}

	#[test]
	fn the_default_shape_is_multi_sine_and_drives_the_flagship() {
		assert_eq!(SignalShape::default(), SignalShape::MultiSine);
		let flagship = InterpolationProfile::interpolation_heavy_irregular();
		assert_eq!(flagship.signal_shape, SignalShape::MultiSine, "the flagship profile keeps the multi-sine signal");
	}

	#[test]
	fn step_is_piecewise_constant_at_two_levels() {
		// The step shape only ever takes its two levels, never a value between —
		// the property that makes forward-fill reconstruct it exactly between edges.
		for i in 0..=1000 {
			let v = SignalShape::Step.evaluate(f64::from(i) / 1000.0);
			assert!((v - 20.0).abs() < 1e-9 || (v - 80.0).abs() < 1e-9, "step must be 20 or 80, got {v}");
		}
	}

	#[test]
	fn changing_the_shape_changes_the_ground_truth() {
		// Two profiles identical but for the signal shape must produce different
		// ground-truth midpoints, proving the knob actually reaches generation.
		let base = SyntheticParams { signal_shape: SignalShape::MultiSine, ..Default::default() };
		let sawtooth = SyntheticParams { signal_shape: SignalShape::Sawtooth, ..base };
		let p_sine = InterpolationProfile::synthetic("sine", base);
		let p_saw = InterpolationProfile::synthetic("saw", sawtooth);
		let mid = p_sine.start() + p_sine.span / 4; // a quarter in, where the shapes differ
		let a = p_sine.clean_signal_at(mid).expect("ground truth");
		let b = p_saw.clean_signal_at(mid).expect("ground truth");
		assert!((a - b).abs() > 1e-6, "different shapes must yield different truth, got {a} vs {b}");
	}

	#[test]
	fn ground_truth_shape_is_some_for_synthetic_and_none_for_line_protocol() {
		let saw = InterpolationProfile::synthetic("saw", SyntheticParams { signal_shape: SignalShape::Sawtooth, ..Default::default() });
		assert_eq!(saw.ground_truth_shape(), Some(SignalShape::Sawtooth), "a synthetic profile reports its shape");
		let lp = InterpolationProfile::from_line_protocol("tsbs-cpu", SAMPLE_LP, "usage", TimestampPrecision::Seconds, Spline::Cubic, Resolution::Minutes).expect("valid payload");
		assert_eq!(lp.ground_truth_shape(), None, "real-world data has no synthetic shape");
	}

	#[test]
	fn from_line_protocol_surfaces_parse_errors() {
		// A structurally malformed line (no field set) must surface as a parse error.
		let err = InterpolationProfile::from_line_protocol("x", "this-is-not-line-protocol\n", "usage", TimestampPrecision::Seconds, Spline::Linear, Resolution::Minutes).expect_err("malformed payload must error");
		assert!(matches!(err, LineProtocolProfileError::Parse(_)), "expected a Parse error, got {err:?}");
	}
}
